### ISSUE TITLE
[Orchestrator] Decouple HTTP protocol from execution node validation

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#10]
Currently in order to validate if a given node URL is valid when creating a given test bed, it mandates that there is a HTTP server running in order to response the validation request. However this should be instead a simple ping command to the provided URL. That is, not a service but an actual reachable IP with a given DNS assigned value.

**Comment by A01221624** [comment]
Perhaps the term **Host** could be used to reduce confusion.

From [RFC3986](https://tools.ietf.org/html/rfc3986#section-3.2.2):
>3.2.2.  Host
>
>   The host subcomponent of authority is identified by an IP literal
>   encapsulated within square brackets, an IPv4 address in dotted-
>   decimal form, or a registered name.  The host subcomponent is case-
>   insensitive.

**Comment by S41nz** [comment]
Hi,

  I agree, indeed must of the distributed computing platforms use hostnames to access nodes, I will update the wiki when Inget back.

Regards

**Comment by erflogo** [comment]
This is specified in the wiki: "If the list is provided and its null or contains null or malformed URLs then an Invalid Argument Exception will be thrown."

In any place the term "host" is mentioned. It is just mentioned to review URLs.

Anyway, I applied this enhancement.

**Comment by erflogo** [comment]
We implemented this enhancement.
