### ISSUE TITLE
[Interpreter] Wrong call to publishTestplan() method

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#12]
Executing the test02 script I get the following error upon publish test_plan() execution:

Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 62, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\interpreter\TBTAFInterpreter.py", line 115, in parseScript
    raise e
AttributeError: 'TBTAFOrchestrator' object has no attribute 'PublishTestPlan'

The method is actually using camel casing: publishTestPlan, please check and adjust.

Thanks

**Comment by luisdani2090** [comment]
hi @S41nz  could you please share the script you are using for tests?

Thanks

**Comment by S41nz** [comment]
Sure:

//TBTAF Integration test 02
//Description:
//1.-Create a simple test suite
//2.-Create a test bed
//3.-Create a TBTAF project to be stored in DB
//4.-Publish the test plan based on the created test suite

myTestBed = create_test_bed()
//After the command above the following output on console is expected:
//New test bed created on: localhost

//Replace TEST_CONTENT_LOCATION by the actual location on the repo for the test TBTestCases
myTestSuite = create_test_suite("C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples")
//After the command above the following output on console is expected:
// For each discovered test
// Test <Test ID> loaded from: <Complete test filepath>
// Then at the end:
// Test suite created with <number of loaded tests> test cases

//Create the test project.
create_new_project(myTestSuite,myTestBed,"TBTAF Smoke test project 02")
//After the command above the following output on console is expected:
//New project created: TBTAF Smoke test project 02
//Number of tests: <Number of contained tests>
//Execution nodes: localhost

//Replace TEST_PLAN_LOCATION by the actual location on the repo for the test plan HTML
publish test_plan(myTestSuite,"C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples\\SmokeTestReport.html",HTML)
//After the command above the following output on console is expected:
//Test plan published at: TEST_PLAN_LOCATION

**Comment by S41nz** [comment]
Fix confirmed
