### ISSUE TITLE
[Interpreter] Wrong getTestCases() method call upon publish test_plan

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#13]
Considering the following script:

//TBTAF Integration test 02
//Description:
//1.-Create a simple test suite
//2.-Create a test bed
//3.-Create a TBTAF project to be stored in DB
//4.-Publish the test plan based on the created test suite

myTestBed = create_test_bed()
//After the command above the following output on console is expected:
//New test bed created on: localhost

//Replace TEST_CONTENT_LOCATION by the actual location on the repo for the test TBTestCases
myTestSuite = create_test_suite("C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples")
//After the command above the following output on console is expected:
// For each discovered test
// Test <Test ID> loaded from: <Complete test filepath>
// Then at the end:
// Test suite created with <number of loaded tests> test cases

//Create the test project.
create_new_project(myTestSuite,myTestBed,"TBTAF Smoke test project 02")
//After the command above the following output on console is expected:
//New project created: TBTAF Smoke test project 02
//Number of tests: <Number of contained tests>
//Execution nodes: localhost

//Replace TEST_PLAN_LOCATION by the actual location on the repo for the test plan HTML
publish test_plan(myTestSuite,"C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples\\SmokeTestReport.html",HTML)
//After the command above the following output on console is expected:
//Test plan published at: TEST_PLAN_LOCATION

If the issue reported on #12 is removed, then I got the following message upon publish test_plan execution:

Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 62, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\interpreter\TBTAFInterpreter.py", line 115, in parseScript
    raise e
AttributeError: 'str' object has no attribute 'getTestCases'

Thanks and regards

**Comment by luisdani2090** [comment]
Hi @S41nz I updated the code, just want to make sure that it works on your end before closing the issues.

 Thanks and regards

**Comment by S41nz** [comment]
I refreshed the code and here is the new Error stack:

Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 62, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\interpreter\TBTAFInterpreter.py", line 116, in parseScript
    raise e
TypeError: cannot concatenate 'str' and 'NoneType' objects

Thanks

**Comment by luisdani2090** [comment]
@S41nz printing more details, I got this error:

  File "C:\Users\Daniel\Desktop\tbtaf\publishe\TBTAFPublisher.py", line 57, in PublishTestPlan
    s_tests = s_tests + "<td>" + testMetaData.getAssetDescription() + "</td>"
TypeError: cannot concatenate 'str' and 'NoneType' objects

**Comment by S41nz** [comment]
Please assign this to the discoverer team, if the minimum test case metadata is not present, the test case must not be loaded at all.

Thanks and regards
