### ISSUE TITLE
[Interpreter] myResult is not defined

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#14]
Hi,

  Using the following script:

//TBTAF Integration test 01
//Description:
//1.-Create a simple test suite
//2.-Create a test bed
//3.-Create a TBTAF project to be stored in DB
//4.-Perform a simple query about the tags contained in the test suite

myTestBed = create_test_bed()
//After the command above the following output on console is expected:
//New test bed created on: localhost

//Replace TEST_CONTENT_LOCATION by the actual location on the repo for the test TBTestCases
myTestSuite = create_test_suite("C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples")
//After the command above the following output on console is expected:
// For each discovered test
// Test <Test ID> loaded from: <Complete test filepath>
// Then at the end:
// Test suite created with <number of loaded tests> test cases

//Create the test project.
create_new_project(myTestSuite,myTestBed,"TBTAF Smoke test project 03")
//After the command above the following output on console is expected:
//New project created: TBTAF Smoke test project 03
//Number of tests: <Number of contained tests>
//Execution nodes: localhost

myResult = execute(myTestSuite,myTestBed)
//After the command above the following output on console is expected:
//Executing: <Test ID> Progress: [0-100%]

//Replace TEST_RESULT_LOCATION by the actual location on the repo for the test result of the test execution
publish test_results(myResult,"C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples\\SmokeResultReport.html",HTML)
//After the command above the following output on console is expected:
//Test result created at: TEST_RESULT_LOCATION

I get the following output after parsing:

Parse Status: Error
Parse MessageError :     File C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\test03.tbtaf,line 32,Description: myResult is not defined.

Thanks and regards

**Comment by luisdani2090** [comment]
There seems to be an inconsistency across de publis test_results command:

In the interpreter wiki it receives a reference to the result object:
publish test_results(Reference to the test result object[,Location of the test report])

However in the current implementation the method receives the reference to the corresponding TestSuite:

PublishResultReport(tbTestSuiteInstance, resultLocation, outputFormat)

Meaning that changing line 32 from:

publish test_results(myResult,"C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\discoverer\samples\SmokeResultReport.html",HTML)

to:
publish test_results(myTestSuite,"C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\discoverer\samples\SmokeResultReport.html",HTML)

Will not produce an error.

**Comment by S41nz** [comment]
Thanks for the feedback, I didnt catched this while documenting the API for the Publisher.

Lets keep it that way for this iteration (passing the test suite) and I will revisit.

Regards
