### ISSUE TITLE
[Executor]

### ISSUE THREAD

**Issue by luisdani2090** [S41nz/TBTAF#15]
The tests don´t execute because the optional parameters

testSuiteFlags,
executorListener

are being treated as mandatory.

**Comment by JuanCalvilloTec** [comment]
Me puedes decir como lo están intentando llamar? los parámetros son opcionales, lo que no es lo mismo a que acepten que les mandes None, si se manda llamar sin poner esos parámetros debe funcionar.

Ejemplo:
  ejecutor = TBTAFExecutor()
    suite = TBTestSuite(1,'A')
    for i in range(5):
        newTest = TBTAFSampleTest()
        suite.addTestCase(newTest)
    ejecutor.executeTests(suite, "dummyBed")

El que no acepte None se basa en la wiki:
"In case of receiving null on any of their inputs, then an Invalid Argument Exception will be thrown."

**Comment by S41nz** [comment]
Hi,

Please bare in mind that those mentioned inputs are optional as specified on the wiki.

I just added the clarification on that exception statement to throw the exception if the inputs are explicitly provided.

Thanks and regards

**Comment by luisdani2090** [comment]
Si tienes razón, se estaban mandando esos para metros como None, gracias!
