### ISSUE TITLE
[Publisher] Published test plan with unsorted tests

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#18]
After executing test02 I see the HTML report published successfully, however the tests cases are not sorted neither by asset id nor priority.

I think we discussed this during class, so if all the test cases contain prioridad specified sort by priority, otherwise sort by asset id.

Thanks and regards

**Comment by S41nz** [comment]
Please refresh to the tip as I introduced a fix to TBSmartTestSuite

**Comment by andresmurob** [comment]
Sorting implemented. If all test cases contain a numeric priority, the sorting is done by priority. Otherwise, its sorted by asset id.
