### ISSUE TITLE
[Executor] Execution of test cases in wrong order

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#20]
Two main issues here:

  The first one is that the cleanup() method for all the test cases is being called prior test execution while it the method should be called at each time a test is being executed.

The second issue is that such calls are in the wrong order and there are also missing calls as well. The right order should be this(per wiki spec):

setup()
execute()
verdict()
cleanup()

Thanks and regards

**Comment by JuanCalvilloTec** [comment]
Could you please tell me where can I find the explanation of where each call should happen, I tried to find about "setup" in common, home, and executor wikis, and didn't find any info (besides it is numbered in the methods of TBTestCase class).

**Comment by S41nz** [comment]
Hi,

  Currently that's the only place where its documented. The ordering of the methods execution was explained during our first session when introducing the project, also it is documented on the TBTestCase code as well.

Hope it helps

Thanks and regards

**Comment by JuanCalvilloTec** [comment]
I'm assuming this:
1. setup is called for each test before any test execute
2. execute is called
3. verdict is called just after the test execution completes

When is cleanup called? I am concerned about it, does that method delete the results? The results are used in the getStatus method which is can be called in any point after the execution completed.

**Comment by S41nz** [comment]
Per the documentation on TBTestCase:

"Method that performs cleanup routines after test execution and verdict calculation. This will get the testing environment ready for the next test to be executed."

So don't worry, this method is supposed to take care of the environment and not touch the verdict of the test.

Thanks and regards

**Comment by JuanCalvilloTec** [comment]
Great. Any script I could run to test the fix?

**Comment by S41nz** [comment]
Sure, 

  Just use test03.tbtaf and point the test suite to the location of tests as described in the issue.

**Comment by JuanCalvilloTec** [comment]
Fix merged.
