### ISSUE TITLE
[Orchestrator] Missing integration for output during test execution

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#21]
Steps to reproduce:

1.- In a specific location add 2..n test case scripts based on the content of TBTAFSampleTest with its corresponding metadata documentation.
2.- Execute the test03 script pointing to the test content location used on previous point.

Expected outcome:

//After the command above the following output on console is expected:
//Executing: <Test ID> Progress: [0-100%]

Actual outcome:

Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Warning :     File C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\test03.tbtaf,line 32,Description: year=1 is before 1900; the datetime strftime() methods require year >= 1900

Parse Status: Success
Parse MessageSuccess
>>> Execute performed from TBTAFSampleTest
Execute performed from TBTAFSampleTest
Execute performed from TBTAFSampleTest
Execute performed from TBTAFSampleTest
Execute performed from TBTAFSampleTest

Two issues here:

1.- I don´t see the % of progress during the execution.
2.- The thread gave back the control to the user even before the tests finished the execution, which means that the parseScript method already exited. This method should give back the control to the user only when all tests finishes their execution.

Thanks and regards

**Comment by erflogo** [comment]
Fixed
