### ISSUE TITLE
[Publisher] Empty test result report

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#23]
Steps to reproduce:

1.- In a specific location add 2..n test case scripts based on the content of TBTAFSampleTest with its corresponding metadata documentation.
2.- Execute the test03 script pointing to the test content location used on previous point.
3.- Publish the test results document via the following command on the script:

//Replace TEST_RESULT_LOCATION by the actual location on the repo for the test result of the test execution
publish test_results(myTestSuite,"C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples\\SmokeResultReport.html",HTML)
//After the command above the following output on console is expected:
//Test result created at: TEST_RESULT_LOCATION

Expected outcome:

  Having the HTML collateral generated @ the specified location.

Actual result:

I'm getting an empty HTML file on the specified location.,

**Comment by S41nz** [comment]
Warning :     File C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\test03.tbtaf,line 32,Description: year=1 is before 1900; the datetime strftime() methods require year >= 1900

Just in case it helps

**Comment by andresmurob** [comment]
While reproducing the issue, we're getting the following:

Welcome to TBTAF Test bed
Executing the following test script: D:\tbtaf\tbtaf\test\test03.tbtaf
Parse Status: Error
Parse MessageError :     File D:\tbtaf\tbtaf\test\test03.tbtaf,line 32,Description: myResult is not defined.

Seems this is actually an issue with the interpreter module while parsing the execute command. Publisher is not being called at all.

**Comment by S41nz** [comment]
Check that the last statement is receiving the myTestSuite instead of myResult object

publish test_results(myTestSuite,"C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\discoverer\samples\SmokeResultReport.html",HTML)

The script on the repo does not have this correction.

**Comment by andresmurob** [comment]
After making that correction, we're getting the following error:

Welcome to TBTAF Test bed
Executing the following test script: D:\tbtaf\tbtaf\test\test03.tbtaf
New test bed created on:  ['127.0.0.1']
Test  testSuiteID_01  loaded from:  D:\\tbtaf\\tbtaf\\test\\discoverer\\samples
Test suite created with  5  test cases
New project created:  TBTAF Smoke test project 03
Number of tests:  5
Execution nodes:  127.0.0.1
Setup performed from TestCompleteAndValidMetadata
Setup performed from TestOnlyRequiredMetadata
Setup performed from TestPriorityAboveLimit
Setup performed from TestPriorityBelowLimit
Setup performed from TestVerdictIsFail
Exception found while executing test 2021. The exception thrown was: 'NoneType' object has no attribute 'setStartTimestamp'
Traceback (most recent call last):

Exception found while executing test 2021. The exception thrown was: 'TestOnlyRequiredMetadata' object has no attribute 'testResult'  File "D:\tbtaf\tbtaf\tbtaf_launcher.py", line 17, in <module>

    parseResult = myTBTAF.parseScript(testScript)
Exception found while executing test 2021. The exception thrown was: 'TestPriorityAboveLimit' object has no attribute 'testResult'  File "D:\tbtaf\tbtaf\orchestrator\TBTAFOrchestrator.py", line 64, in parseScript

    return _interpreter.parseScript(filePath)
Exception found while executing test 2021. The exception thrown was: 'TestPriorityBelowLimit' object has no attribute 'testResult'  File "D:\tbtaf\tbtaf\interpreter\TBTAFInterpreter.py", line 116, in parseScript

    raise e
Exception found while executing test 2021. The exception thrown was: 'TestVerdictIsFail' object has no attribute 'testResult'AttributeError: 'TestOnlyRequiredMetadata' object has no attribute 'testResult'

Cleanup performed from TestCompleteAndValidMetadata
>>> 
Cleanup performed from TestOnlyRequiredMetadata
Cleanup performed from TestPriorityAboveLimit
Cleanup performed from TestPriorityBelowLimit
Cleanup performed from TestVerdictIsFail

The exceptions raised are not related to the publisher module.

**Comment by S41nz** [comment]
Please test loading the content from tbtaf/test/smoke folder

**Comment by andresmurob** [comment]
When loading content from tbtaf/test/smoke folder, we get the following output:

Welcome to TBTAF Test bed
Executing the following test script: D:\tbtaf\tbtaf\test\test03.tbtaf
New test bed created on:  ['127.0.0.1']
Test  testSuiteID_01  loaded from:  D:\\tbtaf\\test\\smoke
Test suite created with  5  test cases
New project created:  TBTAF Smoke test project 03
Number of tests:  5
Execution nodes:  127.0.0.1
Setup performed from TBTAFSampleTest
Setup performed from TBTAFSampleTest
Setup performed from TBTAFSampleTest
Setup performed from TBTAFSampleTest
Setup performed from TBTAFSampleTest
Execution status: Executing
Suite status: Inconclusive
Executed 0/5 : 0.0% completed
1001: Inconclusive
1002: Inconclusive
1003: Inconclusive
1004: Inconclusive
1005: Inconclusive
Execution status: Executing
Suite status: Inconclusive
Executed 0/5 : 0.0% completed
1001: Inconclusive
1002: Inconclusive
1003: Inconclusive
1004: Inconclusive
1005: Inconclusive
Execute performed from TBTAFSampleTest
Execution status: Executing
Suite status: Inconclusive
Executed 1/5 : 20.0% completed
1001: Passed
1002: Inconclusive
1003: Inconclusive
1004: Inconclusive
1005: Inconclusive
Execute performed from TBTAFSampleTest
Execution status: Executing
Suite status: Inconclusive
Executed 2/5 : 40.0% completed
1001: Passed
1002: Passed
1003: Inconclusive
1004: Inconclusive
1005: Inconclusive
Execution status: Executing
Suite status: Inconclusive
Executed 2/5 : 40.0% completed
1001: Passed
1002: Passed
1003: Inconclusive
1004: Inconclusive
1005: Inconclusive
Execute performed from TBTAFSampleTest
Execution status: Executing
Suite status: Inconclusive
Executed 3/5 : 60.0% completed
1001: Passed
1002: Passed
1003: Passed
1004: Inconclusive
1005: Inconclusive
Execute performed from TBTAFSampleTest
Execution status: Executing
Suite status: Inconclusive
Executed 4/5 : 80.0% completed
1001: Passed
1002: Passed
1003: Passed
1004: Passed
1005: Inconclusive
Execute performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Execution status: Completed
Suite status: Passed
Executed 5/5 : 100.0% completed
1001: Passed
1002: Passed
1003: Passed
1004: Passed
1005: Passed

Traceback (most recent call last):
  File "D:\tbtaf\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "D:\tbtaf\tbtaf\orchestrator\TBTAFOrchestrator.py", line 64, in parseScript
    return _interpreter.parseScript(filePath)
  File "D:\tbtaf\tbtaf\interpreter\TBTAFInterpreter.py", line 116, in parseScript
    raise e
AttributeError: 'NoneType' object has no attribute 'strftime'

The exceptions raised are not related to the publisher module.

**Comment by S41nz** [comment]
Got it, so this is duplicate with #27

Closing it
