### ISSUE TITLE
[Orchestrator] NameError: global name 'time' is not defined during execute() statement

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#24]
Hi,

  I just refreshed the latest code and I'm now seeing an exception while executing the smoke test suite. (I just uploaded at TBTAF/test/smoke).

Input script: test03.tbaf

Output:

Welcome to TBTAF Test bed
Executing the following test script: C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\test03.tbtaf
New test bed created on:  ['127.0.0.1']
Test  testSuiteID_01  loaded from:  C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\test\\smoke
Test suite created with  5  test cases
New project created:  TBTAF Smoke test project 03
Number of tests:  5
Execution nodes:  127.0.0.1
Setup performed from TBTAFSampleTest
Setup performed from TBTAFSampleTest
Setup performed from TBTAFSampleTest
Setup performed from TBTAFSampleTest
Setup performed from TBTAFSampleTest
Execution status: Executing
Suite status: Inconclusive
Executed 0/5 : 0.0% completed
1001: Inconclusive
1002: Inconclusive
1003: Inconclusive
1004: Inconclusive
1005: Inconclusive

Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 63, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\interpreter\TBTAFInterpreter.py", line 116, in parseScript
    raise e
NameError: global name 'time' is not defined
>>> Execute performed from TBTAFSampleTest
Execute performed from TBTAFSampleTest
Execute performed from TBTAFSampleTest
Execute performed from TBTAFSampleTest
Execute performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest

**Comment by S41nz** [comment]
Please check and reassign if required

**Comment by erflogo** [comment]
Importing time library.
