### ISSUE TITLE
[Interpreter] TypeError: getTestCases() takes at least 2 arguments (1 given) while executing test01.tbtaf

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#25]
Input script:

myTestBed = create_test_bed()
//After the command above the following output on console is expected:
//New test bed created on: localhost

//Replace TEST_CONTENT_LOCATION by the actual location on the repo for the test TBTestCases
myTestSuite = create_test_suite("C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples",["TBTAF"])
//After the command above the following output on console is expected:
// For each discovered test
// Test <Test ID> loaded from: <Complete test filepath>
// Then at the end:
// Test suite created with <number of loaded tests> test cases

//Create the test project.
create_new_project(myTestSuite,myTestBed,"TBTAF Smoke test project 01")
//After the command above the following output on console is expected:
//New project created: TBTAF Smoke test project 01
//Number of tests: <Number of contained tests>
//Execution nodes: localhost

get_tags("TBTAF Smoke test project 01")
//I should get listed all the tags contained in the test content of the created test suite

//Replace TEST_TAG by one of the tags contained on the created test suite
get_tests("TBTAF Smoke test project 01",["TBTAF"],IN)
//After the command above its expected to display the list of all the test IDs that contained the requested tag above

Actual outcome:

Welcome to TBTAF Test bed
Executing the following test script: C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\test01.tbtaf
New test bed created on:  ['127.0.0.1']
Test  testSuiteID_01  loaded from:  C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples
Smart test suite created with 

Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 63, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\interpreter\TBTAFInterpreter.py", line 116, in parseScript
    raise e
TypeError: getTestCases() takes at least 2 arguments (1 given)

Please reassign if required.

Thanks and regards

**Comment by erflogo** [comment]
@pacoalan is checking this.

**Comment by carofermin** [comment]
TBTAFOrchestrator. My findings:

118- print 'Smart test suite created with ', len(_smartTestSuite.getTestCases()), ' test cases'
57- print 'Number of tests: ', len(tBTestSuiteInstance.getTestCases()) (before printing should validate if is a smart suite)
236 - testCases = tbTestSuiteInstance.getTestCases() (In this case testSuite is an instance of smart suite, if calling 'getTestCases' is needed params are required)

**Comment by pacoalan** [comment]
Thanks @carofermin this was fixed. We changed getTestCases for getTestCasesByTags in smart_suite.py. When we used it in ocrhestrator with tags, we used the new method.
