### ISSUE TITLE
[Orchestrator] AttributeError: 'NoneType' object has no attribute 'strftime'

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#27]
When executing the test03 script I'm getting the following Error right after finalizing the execution of the tests:

Execute performed from TBTAFSampleTest
Execution status: Executing
Suite status: Inconclusive
Executed 4/5 : 80.0% completed
1001: Passed
1002: Passed
1003: Passed
1004: Passed
1005: Inconclusive
Execute performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Cleanup performed from TBTAFSampleTest
Execution status: Completed
Suite status: Passed
Executed 5/5 : 100.0% completed
1001: Passed
1002: Passed
1003: Passed
1004: Passed
1005: Passed

Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\tbtaf_launcher.py", line 17, in <module>
    parseResult = myTBTAF.parseScript(testScript)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 64, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\interpreter\TBTAFInterpreter.py", line 116, in parseScript
    raise e
AttributeError: 'NoneType' object has no attribute 'strftime'

**Comment by erflogo** [comment]
@S41nz We reviewed this and we deided this is not from us. We are not sure if this is for executor or for interpreter. @luisdani2090 @carofermin @JuanCalvilloTec

**Comment by luisdani2090** [comment]
@andresmurob I don't have my computer at hand right now, but I think the error is coming from the publisher.

Could you help me validate this? 

Thanks in advance!

**Comment by S41nz** [comment]
This turned to be an issue with reseting the TBTAFResult object within the SampleTest instances.

Now the report is generated successfully.

Closing the issue.
