### ISSUE TITLE
[Publisher] Please include Project ID and Test Suite ID on the test plan report

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#29]
I consider this information required for production environments, otherwise there is no traceability from the report back to the testing assets from project perspective.

<!DOCTYPE html>
<html>
    <head>
		<title>TBTAF Test Plan</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	</head>
    <body>
        <h2>TBTAF Test Plan</h2>
        <hr/>
        <div class="container">
            <table class="table table-striped">
                <tr class="info">
                <th>Test ID</th>
                <th>Description</th>		
                <th>Tags</th>
                <th>Priority</th>
                </tr>
                <tr><td>1001</td><td>Hello from Sample test 1001</td><td>TBTAF, Smoke, First</td><td>1</td></tr><tr><td>1002</td><td>Hello from Sample test 1002</td><td>TBTAF, Smoke</td><td>2</td></tr><tr><td>1003</td><td>Hello from Sample test 1003</td><td>TBTAF, Smoke</td><td>3</td></tr><tr><td>1004</td><td>Hello from Sample test 1004</td><td>TBTAF, Smoke</td><td>4</td></tr><tr><td>1005</td><td>Hello from Sample test 1005</td><td>TBTAF, Smoke</td><td>5</td></tr>
            </table>
            <hr/>
            <p>Report generated at December 02,2015 16:43:03</p>
        </div>
    </body>
</html>

**Comment by andresmurob** [comment]
I added the test suite ID on the title. There's no reference to the project ID from the test suite we get on the publisher.
