### ISSUE TITLE
[Executor] Simplify console output

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#30]
While performing the integration tests I realized that each time the Orchestrator queries for the result of the execution this information gets dumped into the console:

Execution status: Executing
Suite status: Inconclusive
Executed 3/5 : 60.0% completed
1001: Passed
1002: Passed
1003: Passed
1004: Inconclusive
1005: Inconclusive

When using larget test suites, the actual console dump will become unusable and even cause the execution to be slower. So it will be better if we remove the status info of individual tests, so the output can be like this each time the orchestrator pools for result:

Executed 0/5 : 0.0% completed
Executed 1/5 : 20.0% completed
Executed 2/5 : 40.0% completed
Executed 3/5 : 60.0% completed
Executed 4/5 : 80.0% completed
Executed 5/5 : 100.0% completed

Thanks

**Comment by JuanCalvilloTec** [comment]
Done.
