### ISSUE TITLE
Please remove any hard-coded credentials and implement logic to fetch it from OS environment variables as designed.

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#32]
Please remove any hard-coded credentials and implement logic to fetch it from OS environment variables as designed.

_Originally posted by @S41nz in https://github.com/S41nz/TBTAF/pull/31#discussion_r847830658_

**Comment by davtor94** [comment]
just I pushed by mistake an unwanted file, removed

**Comment by S41nz** [comment]
Thanks
