### ISSUE TITLE
[Orchestrator] Issue with TBTAFDiscoverer import on Eclipse

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#6]
Hi guys,

  Now its compaining about the import on TBTAFDiscoverer:

Traceback (most recent call last):
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\tbtaf_test_bed.py", line 6, in <module>
    from orchestrator import TBTAFOrchestrator
  File "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\orchestrator\TBTAFOrchestrator.py", line 21, in <module>
    from discoverer.discoverer import TBTAFDiscoverer 
ImportError: No module named discoverer

Please check and fix/advice.

Thanks

**Comment by erflogo** [comment]
Unable to replicate this issue. How are you testing this?

**Comment by S41nz** [comment]
From a PyDev environment (on Eclipse). I have a project with the source code from the repo.

Then on the tbtaf/test folder I created a simple Python module with the following:

'''
Created on 25/11/2015

@author: S41nz
'''
from orchestrator import TBTAFOrchestrator

if __name__ == '__main__':
    
    testScript = "C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\test02.tbaf"
    print "Welcome to TBTAF Test bed"
    
    myTBTAF = TBTAFOrchestrator()
    
    print "Executing the following test script: " + testScript
    
    myTBTAF.parseScript(testScript)

Then execute the file and you will get the output I'm observing.

In the meantime, please describe your execution environment

Thanks

**Comment by erflogo** [comment]
I run the file TBTAFOrchestrator_Test.py. It is in this directory TBTAF\tbtaf.

**Comment by S41nz** [comment]
Got it, will attempt later tonight

**Comment by erflogo** [comment]
Btw, I tested the script you send me. And I'm able to run it. But I'm getting an invalid argument exception from Interpreter class:

C:\Users\eriflore\OneDrive\Documentos\Maestria\Semestre3\Procesos_Y_Calidad_De_S
oftware\Project\TBTAF_Repositorio\TBTAF\tbtaf>test.py
Welcome to TBTAF Test bed
Executing the following test script: C:\Users\eriflore\OneDrive\Documentos\Maest
ria\Semestre3\Procesos_Y_Calidad_De_Software\Project\TBTAF_Repositorio\TBTAF
btaf    est     est02.tbaf
Traceback (most recent call last):
  File "C:\Users\eriflore\OneDrive\Documentos\Maestria\Semestre3\Procesos_Y_Cali
dad_De_Software\Project\TBTAF_Repositorio\TBTAF\tbtaf\test.py", line 12, in <mod
ule>
    myTBTAF.parseScript(testScript)
  File "C:\Users\eriflore\OneDrive\Documentos\Maestria\Semestre3\Procesos_Y_Cali
dad_De_Software\Project\TBTAF_Repositorio\TBTAF\tbtaf\orchestrator\TBTAFOrchestr
ator.py", line 61, in parseScript
    return _interpreter.parseScript(filePath)
  File "C:\Users\eriflore\OneDrive\Documentos\Maestria\Semestre3\Procesos_Y_Cali
dad_De_Software\Project\TBTAF_Repositorio\TBTAF\tbtaf\interpreter\TBTAFInterpret
er.py", line 100, in parseScript
    raise InvalidArgumentException(e)
NameError: global name 'InvalidArgumentException' is not defined

This is the code I'm using:

from orchestrator.TBTAFOrchestrator import TBTAFOrchestrator
#if name == 'main':
testScript = "C:\Users\eriflore\OneDrive\Documentos\Maestria\Semestre3\Procesos_Y_Calidad_De_Software\Project\TBTAF_Repositorio\TBTAF\tbtaf\test\test02.tbaf"
print "Welcome to TBTAF Test bed"
myTBTAF = TBTAFOrchestrator()
print "Executing the following test script: " + testScript
myTBTAF.parseScript(testScript)

I'm running it from this directory: TBTAF\tbtaf

Remember change the testScript value.

**Comment by S41nz** [comment]
I was able to get it running without load issues by replicating the recipe and location of TBTAFOrchestrator_Test.py. Now we have further issues to deal with. I will consider this as an env issue
