### ISSUE TITLE
[Interpreter] Actual script execution not happening? Expected console output missing.

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#8]
Using the following test script:

//TBTAF Integration test 01
//Description:
//1.-Create a simple test suite
//2.-Create a test bed
//3.-Create a TBTAF project to be stored in DB
//4.-Perform a simple query about the tags contained in the test suite

myTestBed = create_test_bed("http://localhost")
//After the command above the following output on console is expected:
//New test bed created on: localhost

//Replace TEST_CONTENT_LOCATION by the actual location on the repo for the test TBTestCases
myTestSuite = create_test_suite("C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\discoverer\\samples")
//After the command above the following output on console is expected:
// For each discovered test
// Test <Test ID> loaded from: <Complete test filepath>
// Then at the end:
// Test suite created with <number of loaded tests> test cases

//Create the test project.
create_new_project(myTestSuite,myTestBed,"TBTAF Smoke test project 01")
//After the command above the following output on console is expected:
//New project created: TBTAF Smoke test project 01
//Number of tests: <Number of contained tests>
//Execution nodes: localhost

get_tags("TBTAF Smoke test project 01")
//I should get listed all the tags contained in the test content of the created test suite

//Replace TEST_TAG by one of the tags contained on the created test suite
get_tests("TBTAF Smoke test project 01",["TBTAF"])
//After the command above its expected to display the list of all the test IDs that contained the requested tag above

And executing the following python script under tbtaf location:

'''
Created on 25/11/2015

@author: S41nz
'''
from orchestrator.TBTAFOrchestrator import TBTAFOrchestrator

if __name__ == '__main__':
    
    testScript = "C:\\Users\\psainza\\Documents\\TBTAF\\TBTAF\\tbtaf\\test\\test01.tbtaf"
    print "Welcome to TBTAF Test bed"
    
    myTBTAF = TBTAFOrchestrator()
    
    print "Executing the following test script: " + testScript
    
    myTBTAF.parseScript(testScript)

    print "Execution ended"

I got the following output on console right away:

Welcome to TBTAF Test bed
Executing the following test script: C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\test01.tbtaf
Execution ended

None of the expected output is appearing.

Please investigate and reassign if necessary.

**Comment by carofermin** [comment]
- parseScript is returning an result object with status and message. For printing result use that obj.
- Orchestrator reference has not been set.
- line 31:  get tests("TBTAF Smoke test project 01",["TBTAF"])
missing  parameter. Expected: IN/OUT

iii.	Optional If the list of tags is provided, then an additional enumeration can be passed in order to specify if the tags will be used to filter IN or OUT the results found.

**Comment by S41nz** [comment]
Received, thanks +1:
