### ISSUE TITLE
[Interpreter] create_test_bed syntax not compliant

### ISSUE THREAD

**Issue by S41nz** [S41nz/TBTAF#9]
Per the syntax spec, the create_test_bed parameter is expecting a list of URLs, instead of a single string.

If I put the list as expected: create_test_bed(['http://localhost']) then I receive the following output:

Executing the following test script: C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\test01.tbtaf
Parse Status: Error
Parse MessageError :     File C:\Users\psainza\Documents\TBTAF\TBTAF\tbtaf\test\test01.tbtaf,line 8,Description: Malformed command

Please adjust.

Currently I'm able to make progress as the parameter is currently defaulted within the TBTAFOrchestrator.

Thanks and regards

**Comment by luisdani2090** [comment]
Hi @S41nz I added a fix to accept the specified format.
However the single quotes should be changed for double quotes, as of right now the interpreter only works with double quotes.

Thanks and regards
